/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author DeathRaven1221
 */
public class Sidebar extends javax.swing.JPanel {

    /**
     * Creates new form Sidebar
     */
    public Sidebar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        picture1 = new components.Picture();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        listMenu1 = new view.ListMenu();
        listMenu2 = new view.ListMenu();
        listMenu3 = new view.ListMenu();
        listMenu4 = new view.ListMenu();
        listMenu5 = new view.ListMenu();
        jPanel2 = new javax.swing.JPanel();
        listMenu6 = new view.ListMenu();
        listMenu7 = new view.ListMenu();
        listMenu8 = new view.ListMenu();

        setBackground(new java.awt.Color(243, 243, 243));
        setLayout(null);

        picture1.setPath("/assets/brand.png");
        add(picture1);
        picture1.setBounds(0, 0, 50, 50);

        jLabel1.setFont(new java.awt.Font("Caladea", 1, 21)); // NOI18N
        jLabel1.setText("Miscelanea Bellavista");
        add(jLabel1);
        jLabel1.setBounds(60, 0, 210, 30);

        jPanel1.setBackground(new java.awt.Color(243, 243, 243));
        jPanel1.setLayout(new java.awt.GridLayout(0, 1, 0, 10));
        jPanel1.add(listMenu1);
        jPanel1.add(listMenu2);
        jPanel1.add(listMenu3);
        jPanel1.add(listMenu4);
        jPanel1.add(listMenu5);

        add(jPanel1);
        jPanel1.setBounds(5, 70, 190, 248);

        jPanel2.setBackground(new java.awt.Color(243, 243, 243));
        jPanel2.setLayout(new java.awt.GridLayout(0, 1, 0, 10));
        jPanel2.add(listMenu6);
        jPanel2.add(listMenu7);
        jPanel2.add(listMenu8);

        add(jPanel2);
        jPanel2.setBounds(5, 460, 190, 140);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private view.ListMenu listMenu1;
    private view.ListMenu listMenu2;
    private view.ListMenu listMenu3;
    private view.ListMenu listMenu4;
    private view.ListMenu listMenu5;
    private view.ListMenu listMenu6;
    private view.ListMenu listMenu7;
    private view.ListMenu listMenu8;
    private components.Picture picture1;
    // End of variables declaration//GEN-END:variables
}
